INSERT IGNORE INTO role(role_name)
VALUES ('ROLE_ADMIN');
INSERT IGNORE INTO role(role_name)
VALUES ('ROLE_STUDENT');
INSERT IGNORE INTO role(role_name)
VALUES ('ROLE_TEACHER');
INSERT IGNORE INTO role(role_name)
VALUES ('ROLE_COMPANY');
